use serde::Serialize;
use anyhow::Result;
use std::fs;

pub struct HtmlExporter;

impl HtmlExporter {
    pub fn new() -> Self {
        Self
    }

    pub fn export<T: Serialize>(&self, data: &T, path: &str) -> Result<()> {
        let json_data = serde_json::to_string_pretty(data)?;

        let html = format!(
            r#"<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Code Cost Analysis Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            padding: 30px;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        pre {{
            background: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 4px;
            padding: 15px;
            overflow-x: auto;
        }}
        .footer {{
            margin-top: 30px;
            text-align: center;
            color: #7f8c8d;
            font-size: 14px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 Code Cost Analysis Report</h1>
        <pre>{}</pre>
        <div class="footer">
            Generated by <strong>code-cost</strong> - CLI Tools Collection
        </div>
    </div>
</body>
</html>"#,
            json_data
        );

        fs::write(path, html)?;
        Ok(())
    }
}

impl Default for HtmlExporter {
    fn default() -> Self {
        Self::new()
    }
}
