use serde::Serialize;
use anyhow::Result;
use std::fs;

pub struct MarkdownExporter;

impl MarkdownExporter {
    pub fn new() -> Self {
        Self
    }

    pub fn export<T: Serialize>(&self, data: &T, path: &str) -> Result<()> {
        let json_data = serde_json::to_string_pretty(data)?;

        let markdown = format!(
            r#"# Code Cost Analysis Report

## Analysis Results

```json
{}
```

---

*Generated by **code-cost** - CLI Tools Collection*
"#,
            json_data
        );

        fs::write(path, markdown)?;
        Ok(())
    }
}

impl Default for MarkdownExporter {
    fn default() -> Self {
        Self::new()
    }
}
